### ISSUE TITLE
请问PolarizedSelfAttention的nn.con2d为何不需要nn.Modellist()或nn.Seq的注册？

### ISSUE THREAD

**Issue by zhongqiu1245** [xmu-xiaoma666/External-Attention-pytorch#20]
您好
首先非常感谢您的工作
请问您的PolarizedSelfAttention.py中的nn.con2d为何不需要nn.Modellist()或nn.Seq的注册？
请问不注册会有什么影响吗？
谢谢！

**Comment by xmu-xiaoma666** [comment]
> Seq

这里nn.Conv2d是一个单独的模块，所以不需要用 nn.Seq和其他模块串起来的

**Comment by zhongqiu1245** [comment]
请问不需要nn.Modellist()和nn.Seq这些nn.conv2d也可以被计入训练？

**Comment by xmu-xiaoma666** [comment]
> 请问不需要nn.Modellist()和nn.Seq这些nn.conv2d也可以被计入训练？

nn.Modellist()和nn.Seq只是把多个结构串成一个结构，跟训不训练是无关的。就算用了nn.Modellist()和nn.Seq，但是没有在forward中调用，还是不会训练的。看是否被训练，要看forward中是否调用了这个结构

**Comment by zhongqiu1245** [comment]
好的，谢谢您，我明白了
以及官方的PSA release了
