### ISSUE TITLE
安装

### ISSUE THREAD

**Issue by He9702** [xmu-xiaoma666/External-Attention-pytorch#3]
这个总结的很不错 作者辛苦了   有个问题就是  这个可以通过pip 或者其他方式安装吗 ？   还是说需要将全部代码 git  clone?

**Comment by xmu-xiaoma666** [comment]
感谢您的意见。后面我会学习一下如何将项目打包成pip安装，近几天应该就会在本项目上更新pip安装方式。

**Comment by xmu-xiaoma666** [comment]
> 这个总结的很不错 作者辛苦了 有个问题就是 这个可以通过pip 或者其他方式安装吗 ？ 还是说需要将全部代码 git clone?

感谢您的意见。后面我会学习一下如何将项目打包成pip安装，近几天应该就会在本项目上更新pip安装方式。

**Comment by xmu-xiaoma666** [comment]
> 这个总结的很不错 作者辛苦了 有个问题就是 这个可以通过pip 或者其他方式安装吗 ？ 还是说需要将全部代码 git clone?

pip安装已更新，欢迎使用pip install dlutils_add，来安装本项目

**Comment by He9702** [comment]
作者辛苦了呀    哈哈哈  感谢感谢


| |
贺琪琪
|
|
***@***.***
|
签名由网易邮箱大师定制
在2021年6月12日 ***@***.***> 写道：

这个总结的很不错 作者辛苦了 有个问题就是 这个可以通过pip 或者其他方式安装吗 ？ 还是说需要将全部代码 git clone?

pip安装已更新，欢迎使用pip install dlutils_add，来安装本项目
