### ISSUE TITLE
ModuleNotFoundError: No module named 'attention'

### ISSUE THREAD

**Issue by bolgxh** [xmu-xiaoma666/External-Attention-pytorch#30]
from attention.SelfAttention import ScaledDotProductAttention
ModuleNotFoundError: No module named 'attention'

**Comment by iksooman** [comment]
@bolgxh I met the same issue. 
After adding **sys.path.append(os.path.dirname(os.path.abspath(os.path.dirname(__file__))))** above **from attention.SelfAttention import ScaledDotProductAttention**, the problem was solved.
