### ISSUE TITLE
论文引用

### ISSUE THREAD

**Issue by jb2849** [xmu-xiaoma666/External-Attention-pytorch#31]
您好。我最近在写论文，里面用到了一些您复现的算法。所以说，除了想引用原作者的工作，也想引用您的工作。我是直接引用您的github，还是有相关论文可以引用？ 非常感谢您的代码给我们的研究工作带来了很多便利以及新的想法。

**Comment by xmu-xiaoma666** [comment]
> 您好。我最近在写论文，里面用到了一些您复现的算法。所以说，除了想引用原作者的工作，也想引用您的工作。我是直接引用您的github，还是有相关论文可以引用？ 非常感谢您的代码给我们的研究工作带来了很多便利以及新的想法。

感谢对项目的支持

您可以在脚注，或者参考文献上附上项目的链接

类似这种
![image](https://user-images.githubusercontent.com/33897496/131615167-15467879-0cb8-4b30-81a3-86dd5f67812f.png)

**Comment by jb2849** [comment]
好的，十分感谢！
